h_vs_node:
  ros__parameters:
    # linear and angular velocity gains, eq. 20, paper
    lambda_v: [5., 5., 0.04]
    lambda_w: [0.02, 0.02, 0.2]

    # twist buffer for moving average
    twist_buffer_len: 5
