h_vs_node:
  ros__parameters:
    # linear and angular velocity gains, eq. 20, paper
    lambda_v: [10., 20., 0.5]
    lambda_w: [0.01, 0.01, 0.1]

    # twist buffer for moving average
    twist_buffer_len: 1
